%{
#include <stdio.h>
#include "lex.yy.c"
%}
%token ID EQ_TOK PLUS_TOK MINUS_TOK DIV_TOK MULT_TOK XOR_TOK GREQ_TOK LSEQ_TOK GR_TOK LS_TOK NOT_TOK NOTEQ_TOK AND_TOK OR_TOK IF_TOK ELSE_TOK SWITCH_TOK CASE_TOK FOR_TOK COMMA_TOK SEMICOL_TOK WHILE_TOK LPAREN_TOK RPAREN_TOK RBRACE_TOK LBRACE_TOK 
%%

%%
main()
{

}
